VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.ssh.insert_key = false
  config.vm.hostname = "ala.vagrant.dev"
  config.vm.network :private_network, ip: "10.1.1.4"
  config.vm.network :forwarded_port, guest: 22, host: 2224, id: 'ssh'

  # these machines require some memory to operate the apps
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
  end  
  
end
