# default images variables
image_service_port: 8080
image_service_logfile: logback.groovy
image_service_install_optimisation_packages: false
oxipng_version: "10.1.1"
oxipng_download_base_url: "https://github.com/oxipng/oxipng/releases/download"
